
# This file was *autogenerated* from the file pollard_dlog.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17)#GLOBALS

p = _sage_const_17  
alpha = _sage_const_5 
beta = _sage_const_10 




def order(alpha):
  for i in range (_sage_const_1 ,p):
    if power_mod(alpha,i,p) == _sage_const_1 :
      print "found ord: ", i
      return i

q = order(alpha) # wenn alpha ein Generator ist dann ist ord(alpha) = p-1


def func(s,x,y):
  if _sage_const_0  == mod(s, _sage_const_3 ):
    s_new = mod(alpha*s, p)
    x_new = mod(x+_sage_const_1 ,q)
    y_new = y
    
  if _sage_const_1  == mod(s, _sage_const_3 ):
    s_new = mod(beta*s, p)
    x_new = x
    y_new = mod(y+_sage_const_1 ,q)
    
  if _sage_const_2  == mod(s, _sage_const_3 ):
    s_new = mod(s*s, p)
    x_new = mod(_sage_const_2 *x,q)
    y_new = mod(_sage_const_2 *y,q)

  return s_new, x_new, y_new


def pollardrho():

  K1,K2 = _sage_const_1 ,_sage_const_1 

  s1, x1, y1 = _sage_const_1 ,_sage_const_0 ,_sage_const_0 
  s2, x2, y2 = _sage_const_1 ,_sage_const_0 ,_sage_const_0 
  

  for i in range(_sage_const_1 ,q):
    s1,x1,y1 = func(s1,x1,y1)
    K1 = s1
    
    s2,x2,y2 = func(s2,x2,y2)
    s2,x2,y2 = func(s2,x2,y2)  
    K2 = s2
    #print "K1: ", K1, " K2: ", K2
    
    print "i: ",i ," |s1: ",s1, " x1: ",x1, " y1: ", y1, "| s2: ",s2, " x2: ",x2, " y2: ", y2 , "|" 
    
    if (K1 == K2):
      print "found K: ", K1
      print "x1: ",x1, " y1: ", y1, " x2: ",x2, " y2: ", y2 
      break

  #bruch kuerzen
  x = x1-x2
  y = y2-y1
  
  print "x: ", x, " y: ", y
   
  d = gcd(x,y)
  
  print "d: ",d
  print "q: ",q
  
  v = mod( int(x) / int(d) , q )
  w = mod( int(y) / int(d) , q )
  
  print "v: ", v, " w: ", w
  
  a =  mod( v * pow(w,-_sage_const_1 ,q)  , q)
  print "found a: ", a
  return int(a)


#MAIN#
a = pollardrho()        
restored_beta = power_mod(alpha, a, p)
print "restored_beta: ", restored_beta

